from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import sqlite3
import MiddleWare as MW
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1042, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(750, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(2000, 0))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.setColumnWidth(0,50)
        self.tableWidget.setColumnWidth(1,250)
        self.tableWidget.setColumnWidth(2,170)
        self.tableWidget.setColumnWidth(3,225)
        self.horizontalLayout_11.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ADDFIO = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ADDFIO.setObjectName("ADDFIO")
        self.horizontalLayout.addWidget(self.ADDFIO)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ADDADRESS = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ADDADRESS.setObjectName("ADDADRESS")
        self.horizontalLayout_2.addWidget(self.ADDADRESS)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.TEACHER = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.TEACHER.setObjectName("TEACHER")
        self.horizontalLayout_3.addWidget(self.TEACHER)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.addClass = QtWidgets.QComboBox(parent=self.centralwidget)
        self.addClass.setObjectName("addClass")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
        self.addClass.addItem("")
      
        self.horizontalLayout_4.addWidget(self.addClass)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ADDBUTTON = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.ADDBUTTON.setFont(font)
        self.ADDBUTTON.setStyleSheet("QPushButton {\n"
"background-color:rgba(9, 132, 227,1.0);color:#fff;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:3px solid black;\n"
"}\n"
"")
        self.ADDBUTTON.setObjectName("ADDBUTTON")
        self.verticalLayout.addWidget(self.ADDBUTTON)
        self.ADDBUTTON.clicked.connect(self.addFunction)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.removeClass = QtWidgets.QComboBox(parent=self.centralwidget)
        self.removeClass.setObjectName("removeClass")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.removeClass.addItem("")
        self.horizontalLayout_5.addWidget(self.removeClass)
        self.removeClass.currentIndexChanged.connect(self.ShowRemovedStudent)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.REMOVEFIO = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.REMOVEFIO.sizePolicy().hasHeightForWidth())
        self.REMOVEFIO.setSizePolicy(sizePolicy)
        self.REMOVEFIO.setObjectName("REMOVEFIO")
        self.horizontalLayout_6.addWidget(self.REMOVEFIO)
        self.REMOVEFIO.currentTextChanged.connect(self.getRemovedStudent)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.REMOVEBUTTON = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.REMOVEBUTTON.setFont(font)
        self.REMOVEBUTTON.setStyleSheet("QPushButton {\n"
"background-color:rgba(214, 48, 49,1.0);color:#fff;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:3px solid black;\n"
"}")
        self.REMOVEBUTTON.setObjectName("REMOVEBUTTON")
        self.verticalLayout.addWidget(self.REMOVEBUTTON)
        self.REMOVEBUTTON.clicked.connect(self.removeThis)
        self.line_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.outClass = QtWidgets.QComboBox(parent=self.centralwidget)
        self.outClass.setObjectName("outClass")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.outClass.addItem("")
        self.horizontalLayout_7.addWidget(self.outClass)
        self.outClass.currentIndexChanged.connect(self.ShowTransportStudent)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.DELETEFIO = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DELETEFIO.sizePolicy().hasHeightForWidth())
        self.DELETEFIO.setSizePolicy(sizePolicy)
        self.DELETEFIO.setObjectName("DELETEFIO")
        self.horizontalLayout_8.addWidget(self.DELETEFIO)
        self.DELETEFIO.currentTextChanged.connect(self.getTransportStudent)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.inClass = QtWidgets.QComboBox(parent=self.centralwidget)
        self.inClass.setObjectName("inClass")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.inClass.addItem("")
        self.horizontalLayout_9.addWidget(self.inClass)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.DELETEBUTTON = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.DELETEBUTTON.setFont(font)
        self.DELETEBUTTON.setStyleSheet("QPushButton {\n"
"background-color:rgba(240, 147, 43,1.0);color:#fff;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:3px solid black;\n"
"}")
        self.DELETEBUTTON.setObjectName("DELETEBUTTON")
        self.verticalLayout.addWidget(self.DELETEBUTTON)
        self.DELETEBUTTON.clicked.connect(self.transport)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setStyleSheet("font-size:18px;font-weight:bold")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Excel = QtGui.QAction(parent=MainWindow)
        self.action_Excel.setObjectName("action_Excel")
        self.menu.addAction(self.action_Excel)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Посещаемость школы"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Классный руководитель"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "5А"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Иванова И"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "г.Фергана Сакокий 16"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Петрова Татьяна Александровна"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Ф.И.О"))
        self.label_2.setText(_translate("MainWindow", "Адрес:"))
        self.label_3.setText(_translate("MainWindow", "Класс.рук:"))
        self.label_4.setText(_translate("MainWindow", "Класс:"))
        self.addClass.setItemText(0, _translate("MainWindow", "-"))
        self.addClass.setItemText(1, _translate("MainWindow", "1А"))
        self.addClass.setItemText(2, _translate("MainWindow", "1Б"))
        self.addClass.setItemText(3, _translate("MainWindow", "1В"))
        self.addClass.setItemText(4, _translate("MainWindow", "1Г"))
        self.addClass.setItemText(5, _translate("MainWindow", "1Д"))
        self.addClass.setItemText(6, _translate("MainWindow", "1Е"))
        self.addClass.setItemText(7, _translate("MainWindow", "1Ж"))
        self.addClass.setItemText(8, _translate("MainWindow", "1З"))
        self.addClass.setItemText(9, _translate("MainWindow", "2А"))
        self.addClass.setItemText(10, _translate("MainWindow", "2Б"))
        self.addClass.setItemText(11, _translate("MainWindow", "2В"))
        self.addClass.setItemText(12, _translate("MainWindow", "2Г"))
        self.addClass.setItemText(13, _translate("MainWindow", "2Д"))
        self.addClass.setItemText(14, _translate("MainWindow", "3А"))
        self.addClass.setItemText(15, _translate("MainWindow", "3Б"))
        self.addClass.setItemText(16, _translate("MainWindow", "3В"))
        self.addClass.setItemText(17, _translate("MainWindow", "3Г"))
        self.addClass.setItemText(18, _translate("MainWindow", "3Д"))
        self.addClass.setItemText(19, _translate("MainWindow", "3Е"))
        self.addClass.setItemText(20, _translate("MainWindow", "4А"))
        self.addClass.setItemText(21, _translate("MainWindow", "4Б"))
        self.addClass.setItemText(22, _translate("MainWindow", "4В"))
        self.addClass.setItemText(23, _translate("MainWindow", "4Г"))
        self.addClass.setItemText(24, _translate("MainWindow", "4Д"))
        self.addClass.setItemText(25, _translate("MainWindow", "4Е"))
        self.addClass.setItemText(26, _translate("MainWindow", "4Ж"))
        self.addClass.setItemText(27, _translate("MainWindow", "4З"))
        self.addClass.setItemText(28, _translate("MainWindow", "5А"))
        self.addClass.setItemText(29, _translate("MainWindow", "5Б"))
        self.addClass.setItemText(30, _translate("MainWindow", "5В"))
        self.addClass.setItemText(31, _translate("MainWindow", "5Г"))
        self.addClass.setItemText(32, _translate("MainWindow", "5Д"))
        self.addClass.setItemText(33, _translate("MainWindow", "5Е"))
        self.addClass.setItemText(34, _translate("MainWindow", "5Ж"))
        self.addClass.setItemText(35, _translate("MainWindow", "5З"))
        self.addClass.setItemText(36, _translate("MainWindow", "6А"))
        self.addClass.setItemText(37, _translate("MainWindow", "6Б"))
        self.addClass.setItemText(38, _translate("MainWindow", "6В"))
        self.addClass.setItemText(39, _translate("MainWindow", "6Г"))
        self.addClass.setItemText(40, _translate("MainWindow", "7А"))
        self.addClass.setItemText(41, _translate("MainWindow", "7Б"))
        self.addClass.setItemText(42, _translate("MainWindow", "7В"))
        self.addClass.setItemText(43, _translate("MainWindow", "8А"))
        self.addClass.setItemText(44, _translate("MainWindow", "8Б"))
        self.addClass.setItemText(45, _translate("MainWindow", "8В"))
        self.addClass.setItemText(46, _translate("MainWindow", "8Г"))
        self.addClass.setItemText(47, _translate("MainWindow", "8Д"))
        self.addClass.setItemText(48, _translate("MainWindow", "8Е"))
        self.addClass.setItemText(49, _translate("MainWindow", "8Ж"))
        self.addClass.setItemText(50, _translate("MainWindow", "8З"))
        self.addClass.setItemText(51, _translate("MainWindow", "8И"))
        self.addClass.setItemText(52, _translate("MainWindow", "8К"))
        self.addClass.setItemText(53, _translate("MainWindow", "8Л"))
        self.addClass.setItemText(54, _translate("MainWindow", "9Б"))
        self.addClass.setItemText(55, _translate("MainWindow", "9В"))
        self.addClass.setItemText(56, _translate("MainWindow", "9Г"))
        self.addClass.setItemText(57, _translate("MainWindow", "9Д"))
        self.addClass.setItemText(58, _translate("MainWindow", "9Е"))
        self.addClass.setItemText(59, _translate("MainWindow", "9Ж"))
        self.addClass.setItemText(60, _translate("MainWindow", "9К"))
        self.addClass.setItemText(61, _translate("MainWindow", "10А"))
        self.addClass.setItemText(62, _translate("MainWindow", "10Б"))
        self.addClass.setItemText(63, _translate("MainWindow", "10В"))
        self.addClass.setItemText(64, _translate("MainWindow", "10Г"))
        self.addClass.setItemText(65, _translate("MainWindow", "10Д"))
        self.addClass.setItemText(66, _translate("MainWindow", "10Е"))
        self.addClass.setItemText(67, _translate("MainWindow", "11А"))
        self.addClass.setItemText(68, _translate("MainWindow", "11Б"))
        self.addClass.setItemText(69, _translate("MainWindow", "11В"))
        self.addClass.setItemText(70, _translate("MainWindow", "11Г"))
        self.addClass.setItemText(71, _translate("MainWindow", "11З"))
        self.ADDBUTTON.setText(_translate("MainWindow", "Добавить"))
        self.label_5.setText(_translate("MainWindow", "Класс:"))
        self.removeClass.setItemText(0, _translate("MainWindow", "-"))
        self.removeClass.setItemText(1, _translate("MainWindow", "1А"))
        self.removeClass.setItemText(2, _translate("MainWindow", "1Б"))
        self.removeClass.setItemText(3, _translate("MainWindow", "1В"))
        self.removeClass.setItemText(4, _translate("MainWindow", "1Г"))
        self.removeClass.setItemText(5, _translate("MainWindow", "1Д"))
        self.removeClass.setItemText(6, _translate("MainWindow", "1Е"))
        self.removeClass.setItemText(7, _translate("MainWindow", "1Ж"))
        self.removeClass.setItemText(8, _translate("MainWindow", "1З"))
        self.removeClass.setItemText(9, _translate("MainWindow", "2А"))
        self.removeClass.setItemText(10, _translate("MainWindow", "2Б"))
        self.removeClass.setItemText(11, _translate("MainWindow", "2В"))
        self.removeClass.setItemText(12, _translate("MainWindow", "2Г"))
        self.removeClass.setItemText(13, _translate("MainWindow", "2Д"))
        self.removeClass.setItemText(14, _translate("MainWindow", "3А"))
        self.removeClass.setItemText(15, _translate("MainWindow", "3Б"))
        self.removeClass.setItemText(16, _translate("MainWindow", "3В"))
        self.removeClass.setItemText(17, _translate("MainWindow", "3Г"))
        self.removeClass.setItemText(18, _translate("MainWindow", "3Д"))
        self.removeClass.setItemText(19, _translate("MainWindow", "3Е"))
        self.removeClass.setItemText(20, _translate("MainWindow", "4А"))
        self.removeClass.setItemText(21, _translate("MainWindow", "4Б"))
        self.removeClass.setItemText(22, _translate("MainWindow", "4В"))
        self.removeClass.setItemText(23, _translate("MainWindow", "4Г"))
        self.removeClass.setItemText(24, _translate("MainWindow", "4Д"))
        self.removeClass.setItemText(25, _translate("MainWindow", "4Е"))
        self.removeClass.setItemText(26, _translate("MainWindow", "4Ж"))
        self.removeClass.setItemText(27, _translate("MainWindow", "4З"))
        self.removeClass.setItemText(28, _translate("MainWindow", "5А"))
        self.removeClass.setItemText(29, _translate("MainWindow", "5Б"))
        self.removeClass.setItemText(30, _translate("MainWindow", "5В"))
        self.removeClass.setItemText(31, _translate("MainWindow", "5Г"))
        self.removeClass.setItemText(32, _translate("MainWindow", "5Д"))
        self.removeClass.setItemText(33, _translate("MainWindow", "5Е"))
        self.removeClass.setItemText(34, _translate("MainWindow", "5Ж"))
        self.removeClass.setItemText(35, _translate("MainWindow", "5З"))
        self.removeClass.setItemText(36, _translate("MainWindow", "6А"))
        self.removeClass.setItemText(37, _translate("MainWindow", "6Б"))
        self.removeClass.setItemText(38, _translate("MainWindow", "6В"))
        self.removeClass.setItemText(39, _translate("MainWindow", "6Г"))
        self.removeClass.setItemText(40, _translate("MainWindow", "7А"))
        self.removeClass.setItemText(41, _translate("MainWindow", "7Б"))
        self.removeClass.setItemText(42, _translate("MainWindow", "7В"))
        self.removeClass.setItemText(43, _translate("MainWindow", "8А"))
        self.removeClass.setItemText(44, _translate("MainWindow", "8Б"))
        self.removeClass.setItemText(45, _translate("MainWindow", "8В"))
        self.removeClass.setItemText(46, _translate("MainWindow", "8Г"))
        self.removeClass.setItemText(47, _translate("MainWindow", "8Д"))
        self.removeClass.setItemText(48, _translate("MainWindow", "8Е"))
        self.removeClass.setItemText(49, _translate("MainWindow", "8Ж"))
        self.removeClass.setItemText(50, _translate("MainWindow", "8З"))
        self.removeClass.setItemText(51, _translate("MainWindow", "8И"))
        self.removeClass.setItemText(52, _translate("MainWindow", "8К"))
        self.removeClass.setItemText(53, _translate("MainWindow", "8Л"))
        self.removeClass.setItemText(54, _translate("MainWindow", "9Б"))
        self.removeClass.setItemText(55, _translate("MainWindow", "9В"))
        self.removeClass.setItemText(56, _translate("MainWindow", "9Г"))
        self.removeClass.setItemText(57, _translate("MainWindow", "9Д"))
        self.removeClass.setItemText(58, _translate("MainWindow", "9Е"))
        self.removeClass.setItemText(59, _translate("MainWindow", "9Ж"))
        self.removeClass.setItemText(60, _translate("MainWindow", "9К"))
        self.removeClass.setItemText(61, _translate("MainWindow", "10А"))
        self.removeClass.setItemText(62, _translate("MainWindow", "10Б"))
        self.removeClass.setItemText(63, _translate("MainWindow", "10В"))
        self.removeClass.setItemText(64, _translate("MainWindow", "10Г"))
        self.removeClass.setItemText(65, _translate("MainWindow", "10Д"))
        self.removeClass.setItemText(66, _translate("MainWindow", "10Е"))
        self.removeClass.setItemText(67, _translate("MainWindow", "11А"))
        self.removeClass.setItemText(68, _translate("MainWindow", "11Б"))
        self.removeClass.setItemText(69, _translate("MainWindow", "11В"))
        self.removeClass.setItemText(70, _translate("MainWindow", "11Г"))
        self.removeClass.setItemText(71, _translate("MainWindow", "11З"))
        self.outClass.setItemText(0, _translate("MainWindow", "-"))
        self.outClass.setItemText(1, _translate("MainWindow", "1А"))
        self.outClass.setItemText(2, _translate("MainWindow", "1Б"))
        self.outClass.setItemText(3, _translate("MainWindow", "1В"))
        self.outClass.setItemText(4, _translate("MainWindow", "1Г"))
        self.outClass.setItemText(5, _translate("MainWindow", "1Д"))
        self.outClass.setItemText(6, _translate("MainWindow", "1Е"))
        self.outClass.setItemText(7, _translate("MainWindow", "1Ж"))
        self.outClass.setItemText(8, _translate("MainWindow", "1З"))
        self.outClass.setItemText(9, _translate("MainWindow", "2А"))
        self.outClass.setItemText(10, _translate("MainWindow", "2Б"))
        self.outClass.setItemText(11, _translate("MainWindow", "2В"))
        self.outClass.setItemText(12, _translate("MainWindow", "2Г"))
        self.outClass.setItemText(13, _translate("MainWindow", "2Д"))
        self.outClass.setItemText(14, _translate("MainWindow", "3А"))
        self.outClass.setItemText(15, _translate("MainWindow", "3Б"))
        self.outClass.setItemText(16, _translate("MainWindow", "3В"))
        self.outClass.setItemText(17, _translate("MainWindow", "3Г"))
        self.outClass.setItemText(18, _translate("MainWindow", "3Д"))
        self.outClass.setItemText(19, _translate("MainWindow", "3Е"))
        self.outClass.setItemText(20, _translate("MainWindow", "4А"))
        self.outClass.setItemText(21, _translate("MainWindow", "4Б"))
        self.outClass.setItemText(22, _translate("MainWindow", "4В"))
        self.outClass.setItemText(23, _translate("MainWindow", "4Г"))
        self.outClass.setItemText(24, _translate("MainWindow", "4Д"))
        self.outClass.setItemText(25, _translate("MainWindow", "4Е"))
        self.outClass.setItemText(26, _translate("MainWindow", "4Ж"))
        self.outClass.setItemText(27, _translate("MainWindow", "4З"))
        self.outClass.setItemText(28, _translate("MainWindow", "5А"))
        self.outClass.setItemText(29, _translate("MainWindow", "5Б"))
        self.outClass.setItemText(30, _translate("MainWindow", "5В"))
        self.outClass.setItemText(31, _translate("MainWindow", "5Г"))
        self.outClass.setItemText(32, _translate("MainWindow", "5Д"))
        self.outClass.setItemText(33, _translate("MainWindow", "5Е"))
        self.outClass.setItemText(34, _translate("MainWindow", "5Ж"))
        self.outClass.setItemText(35, _translate("MainWindow", "5З"))
        self.outClass.setItemText(36, _translate("MainWindow", "6А"))
        self.outClass.setItemText(37, _translate("MainWindow", "6Б"))
        self.outClass.setItemText(38, _translate("MainWindow", "6В"))
        self.outClass.setItemText(39, _translate("MainWindow", "6Г"))
        self.outClass.setItemText(40, _translate("MainWindow", "7А"))
        self.outClass.setItemText(41, _translate("MainWindow", "7Б"))
        self.outClass.setItemText(42, _translate("MainWindow", "7В"))
        self.outClass.setItemText(43, _translate("MainWindow", "8А"))
        self.outClass.setItemText(44, _translate("MainWindow", "8Б"))
        self.outClass.setItemText(45, _translate("MainWindow", "8В"))
        self.outClass.setItemText(46, _translate("MainWindow", "8Г"))
        self.outClass.setItemText(47, _translate("MainWindow", "8Д"))
        self.outClass.setItemText(48, _translate("MainWindow", "8Е"))
        self.outClass.setItemText(49, _translate("MainWindow", "8Ж"))
        self.outClass.setItemText(50, _translate("MainWindow", "8З"))
        self.outClass.setItemText(51, _translate("MainWindow", "8И"))
        self.outClass.setItemText(52, _translate("MainWindow", "8К"))
        self.outClass.setItemText(53, _translate("MainWindow", "8Л"))
        self.outClass.setItemText(54, _translate("MainWindow", "9Б"))
        self.outClass.setItemText(55, _translate("MainWindow", "9В"))
        self.outClass.setItemText(56, _translate("MainWindow", "9Г"))
        self.outClass.setItemText(57, _translate("MainWindow", "9Д"))
        self.outClass.setItemText(58, _translate("MainWindow", "9Е"))
        self.outClass.setItemText(59, _translate("MainWindow", "9Ж"))
        self.outClass.setItemText(60, _translate("MainWindow", "9К"))
        self.outClass.setItemText(61, _translate("MainWindow", "10А"))
        self.outClass.setItemText(62, _translate("MainWindow", "10Б"))
        self.outClass.setItemText(63, _translate("MainWindow", "10В"))
        self.outClass.setItemText(64, _translate("MainWindow", "10Г"))
        self.outClass.setItemText(65, _translate("MainWindow", "10Д"))
        self.outClass.setItemText(66, _translate("MainWindow", "10Е"))
        self.outClass.setItemText(67, _translate("MainWindow", "11А"))
        self.outClass.setItemText(68, _translate("MainWindow", "11Б"))
        self.outClass.setItemText(69, _translate("MainWindow", "11В"))
        self.outClass.setItemText(70, _translate("MainWindow", "11Г"))
        self.outClass.setItemText(71, _translate("MainWindow", "11З"))
        self.inClass.setItemText(0, _translate("MainWindow", "-"))
        self.inClass.setItemText(1, _translate("MainWindow", "1А"))
        self.inClass.setItemText(2, _translate("MainWindow", "1Б"))
        self.inClass.setItemText(3, _translate("MainWindow", "1В"))
        self.inClass.setItemText(4, _translate("MainWindow", "1Г"))
        self.inClass.setItemText(5, _translate("MainWindow", "1Д"))
        self.inClass.setItemText(6, _translate("MainWindow", "1Е"))
        self.inClass.setItemText(7, _translate("MainWindow", "1Ж"))
        self.inClass.setItemText(8, _translate("MainWindow", "1З"))
        self.inClass.setItemText(9, _translate("MainWindow", "2А"))
        self.inClass.setItemText(10, _translate("MainWindow", "2Б"))
        self.inClass.setItemText(11, _translate("MainWindow", "2В"))
        self.inClass.setItemText(12, _translate("MainWindow", "2Г"))
        self.inClass.setItemText(13, _translate("MainWindow", "2Д"))
        self.inClass.setItemText(14, _translate("MainWindow", "3А"))
        self.inClass.setItemText(15, _translate("MainWindow", "3Б"))
        self.inClass.setItemText(16, _translate("MainWindow", "3В"))
        self.inClass.setItemText(17, _translate("MainWindow", "3Г"))
        self.inClass.setItemText(18, _translate("MainWindow", "3Д"))
        self.inClass.setItemText(19, _translate("MainWindow", "3Е"))
        self.inClass.setItemText(20, _translate("MainWindow", "4А"))
        self.inClass.setItemText(21, _translate("MainWindow", "4Б"))
        self.inClass.setItemText(22, _translate("MainWindow", "4В"))
        self.inClass.setItemText(23, _translate("MainWindow", "4Г"))
        self.inClass.setItemText(24, _translate("MainWindow", "4Д"))
        self.inClass.setItemText(25, _translate("MainWindow", "4Е"))
        self.inClass.setItemText(26, _translate("MainWindow", "4Ж"))
        self.inClass.setItemText(27, _translate("MainWindow", "4З"))
        self.inClass.setItemText(28, _translate("MainWindow", "5А"))
        self.inClass.setItemText(29, _translate("MainWindow", "5Б"))
        self.inClass.setItemText(30, _translate("MainWindow", "5В"))
        self.inClass.setItemText(31, _translate("MainWindow", "5Г"))
        self.inClass.setItemText(32, _translate("MainWindow", "5Д"))
        self.inClass.setItemText(33, _translate("MainWindow", "5Е"))
        self.inClass.setItemText(34, _translate("MainWindow", "5Ж"))
        self.inClass.setItemText(35, _translate("MainWindow", "5З"))
        self.inClass.setItemText(36, _translate("MainWindow", "6А"))
        self.inClass.setItemText(37, _translate("MainWindow", "6Б"))
        self.inClass.setItemText(38, _translate("MainWindow", "6В"))
        self.inClass.setItemText(39, _translate("MainWindow", "6Г"))
        self.inClass.setItemText(40, _translate("MainWindow", "7А"))
        self.inClass.setItemText(41, _translate("MainWindow", "7Б"))
        self.inClass.setItemText(42, _translate("MainWindow", "7В"))
        self.inClass.setItemText(43, _translate("MainWindow", "8А"))
        self.inClass.setItemText(44, _translate("MainWindow", "8Б"))
        self.inClass.setItemText(45, _translate("MainWindow", "8В"))
        self.inClass.setItemText(46, _translate("MainWindow", "8Г"))
        self.inClass.setItemText(47, _translate("MainWindow", "8Д"))
        self.inClass.setItemText(48, _translate("MainWindow", "8Е"))
        self.inClass.setItemText(49, _translate("MainWindow", "8Ж"))
        self.inClass.setItemText(50, _translate("MainWindow", "8З"))
        self.inClass.setItemText(51, _translate("MainWindow", "8И"))
        self.inClass.setItemText(52, _translate("MainWindow", "8К"))
        self.inClass.setItemText(53, _translate("MainWindow", "8Л"))
        self.inClass.setItemText(54, _translate("MainWindow", "9Б"))
        self.inClass.setItemText(55, _translate("MainWindow", "9В"))
        self.inClass.setItemText(56, _translate("MainWindow", "9Г"))
        self.inClass.setItemText(57, _translate("MainWindow", "9Д"))
        self.inClass.setItemText(58, _translate("MainWindow", "9Е"))
        self.inClass.setItemText(59, _translate("MainWindow", "9Ж"))
        self.inClass.setItemText(60, _translate("MainWindow", "9К"))
        self.inClass.setItemText(61, _translate("MainWindow", "10А"))
        self.inClass.setItemText(62, _translate("MainWindow", "10Б"))
        self.inClass.setItemText(63, _translate("MainWindow", "10В"))
        self.inClass.setItemText(64, _translate("MainWindow", "10Г"))
        self.inClass.setItemText(65, _translate("MainWindow", "10Д"))
        self.inClass.setItemText(66, _translate("MainWindow", "10Е"))
        self.inClass.setItemText(67, _translate("MainWindow", "11А"))
        self.inClass.setItemText(68, _translate("MainWindow", "11Б"))
        self.inClass.setItemText(69, _translate("MainWindow", "11В"))
        self.inClass.setItemText(70, _translate("MainWindow", "11Г"))
        self.inClass.setItemText(71, _translate("MainWindow", "11З"))
        self.label_6.setText(_translate("MainWindow", "Ученик:"))
        self.REMOVEBUTTON.setText(_translate("MainWindow", "Удалить"))
        self.label_7.setText(_translate("MainWindow", "Из класса:"))
        self.label_8.setText(_translate("MainWindow", "Ученик:"))
        self.label_9.setText(_translate("MainWindow", "Перевести в класс:"))
        self.DELETEBUTTON.setText(_translate("MainWindow", "Перевести"))
        count = self.studentCount()
        self.label_10.setText(_translate("MainWindow", f"Количество учеников:    {str(count)}"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action_Excel.setText(_translate("MainWindow", "Экспортировать в Excel"))
        self.show()
    # SHOW FROM DB
    def show_current_class(self,class_value,entry):
        connection = sqlite3.connect("Database.db")
        cur = connection.cursor()
        sql = "SELECT FIO FROM data WHERE Class = ?"
        entry.clear()
        for row in cur.execute(sql, (class_value,)):
                entry.addItems(row)
    def show(self):
        try:
            connection = sqlite3.connect("Database.db")
            cur = connection.cursor()
            sql = "SELECT * FROM data LIMIT 2500"
            self.tableWidget.setRowCount(2500)
            index = 0
            for row in cur.execute(sql):
                self.tableWidget.setItem(index, 0, QtWidgets.QTableWidgetItem(str(row[1])))
                self.tableWidget.setItem(index, 1, QtWidgets.QTableWidgetItem(str(row[2])))
                self.tableWidget.setItem(index, 2, QtWidgets.QTableWidgetItem(str(row[3])))
                self.tableWidget.setItem(index, 3, QtWidgets.QTableWidgetItem(str(row[4])))
               
                index+=1
                # print(row)
        except sqlite3.Error as error:
                print(f"Connection error - {error}")
        finally:
                print("Show information...")
    #  
    #ADD FUNCTION
    def addFunction(self):
        addFIOitem = self.ADDFIO.text()
        addADRESitem = self.ADDADRESS.text()
        addTEACHERitem = self.TEACHER.text()
        addCLASSitem = self.addClass.currentText()
        try: 
            if addFIOitem != '' and addADRESitem != '' and addTEACHERitem != '' and addCLASSitem != '':
                db = sqlite3.connect('DataBase.db')
                print("Подключен к SQLite")
                query = """
                    INSERT INTO data(Class,FIO,Adres,Teacher)
                    VALUES (?,?,?,?)
                    """
                cur = db.cursor()
                cur.execute(query, (addCLASSitem,addFIOitem,addADRESitem,addTEACHERitem))
                db.commit()
                print("Запись успешно вставлена ​​в таблицу Information ")
                db.close()
                print("Соединение с SQLite закрыто")
                msgBox = QMessageBox()
                msgBox.setWindowTitle("Сообщение")
                msgBox.setText("Ученик добавлен!")
                msgBox.exec() 
            else:
                msgBox = QMessageBox()
                msgBox.setWindowTitle("Сообщение")
                msgBox.setText("Заполните все поля!")
                msgBox.exec()
        except sqlite3.Error as error:
            print(error)
            msgBox = QMessageBox()
            msgBox.setWindowTitle("Сообщение")
            msgBox.setText("Произошла Ошибка!")
            msgBox.exec() 
        finally:
            self.ADDFIO.setText(None)
            self.ADDADRESS.setText(None)
            self.TEACHER.setText(None)
            self.addClass.setCurrentText("-") 
            self.show() 
    #
    #REMOVE FUNCTION
    def ShowRemovedStudent(self):
        index = self.removeClass.currentIndex()
        class_value = self.removeClass.currentText()
        if index == 0:
            self.REMOVEFIO.clear()
        else:
            for i in range(1,72):
                if index==i:
                    self.show_current_class(class_value,self.REMOVEFIO)
    def getRemovedStudent(self):
        return self.REMOVEFIO.currentText()
    def removeThis(self):
        try: 
            getStudent = self.getRemovedStudent()
            db = sqlite3.connect('DataBase.db')
            print("Подключен к SQLite")
            cur = db.cursor()
            cur.execute('DELETE FROM data WHERE FIO = ?', (getStudent,))
            db.commit()
            print("Запись успешно удалена из таблицы")
            db.close()
            self.show()
            print("Соединение с SQLite закрыто")
            msgBox = QMessageBox()
            msgBox.setWindowTitle("Сообщение")
            msgBox.setText("Ученик Удален!")
            msgBox.exec()
            
        except sqlite3.Error as error:
            print(error)
            msgBox = QMessageBox()
            msgBox.setWindowTitle("Сообщение")
            msgBox.setText("Произошла Ошибка!")
            msgBox.exec() 
        finally:
            self.removeClass.setCurrentText("-")
            self.REMOVEFIO.clear()
            self.show()
    # 
    # TRANSPORT FUNCTION
    def ShowTransportStudent(self):
        index = self.outClass.currentIndex()
        current_class = self.outClass.currentText()
        if index == 0:
            self.DELETEFIO.clear()
        else:
            for i in range(1,72):
                if index==i:
                    self.show_current_class(current_class,self.DELETEFIO)
    def getTransportStudent(self):
        return self.DELETEFIO.currentText()
    def getInClass(self):
        return self.inClass.currentText()
    def transport(self):
        transport_student = self.getTransportStudent()
        inClass = self.getInClass()
        try:
            connection = sqlite3.connect("DataBase.db")
            cursor = connection.cursor()
            cursor.execute('UPDATE data SET Class = ? WHERE FIO = ?',(inClass,transport_student))
            connection.commit()
            connection.close()
            self.show()
            msgBox = QMessageBox()
            msgBox.setWindowTitle("Сообщение")
            msgBox.setText(f"Ученик переведен в {inClass} класс!")
            msgBox.exec() 
        except sqlite3.Error as error:
            print("Error",error)
    #
    def studentCount(self):
        try:
            connection = sqlite3.connect("DataBase.db")
            cursor = connection.cursor()
            cursor.execute('SELECT COUNT(*) FROM data')
            count = cursor.fetchone()[0]
            connection.close()
            return count
        except sqlite3.Error as error:
            print("Error",error)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
